#!/usr/bin/env bash
set -Eeuo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"
source "$REPO_ROOT/configs/course.env"

log()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[!]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[x]\033[0m %s\n' "$*" >&2; exit 1; }

command -v docker >/dev/null || die "docker not found on PATH"
docker info >/dev/null 2>&1 || die "Docker is not running. Start Docker and retry."
case "$FLOCI_HOST_DATA_DIR" in
  /*) ;;
  *)  die "FLOCI_HOST_DATA_DIR must be ABSOLUTE, got: $FLOCI_HOST_DATA_DIR" ;;
esac

if docker container inspect "$FLOCI_CONTAINER_NAME" >/dev/null 2>&1; then
  owner="$(docker container inspect "$FLOCI_CONTAINER_NAME" \
            --format '{{ index .Config.Labels "com.docker.compose.project" }}' 2>/dev/null || true)"
  if [ "$owner" != "$FLOCI_COMPOSE_PROJECT" ]; then
    warn "A container named '$FLOCI_CONTAINER_NAME' exists but Compose did not create it."
    warn "Remove it, then re-run this script:"
    warn "    floci stop --remove      # or:  docker rm -f $FLOCI_CONTAINER_NAME"
    die  "Refusing to continue."
  fi
fi

mkdir -p "$FLOCI_HOST_DATA_DIR"
log "State directory: $FLOCI_HOST_DATA_DIR"

cat > "$REPO_ROOT/.env" <<ENVEOF
# GENERATED by scripts/setup/floci-up.sh — do not edit, do not commit.
FLOCI_HOST_DATA_DIR=$FLOCI_HOST_DATA_DIR
FLOCI_STORAGE_MODE=$FLOCI_STORAGE_MODE
ENVEOF

log "Starting Floci (storage mode: $FLOCI_STORAGE_MODE)"
docker compose up -d

log "Waiting for the AWS endpoint to become healthy..."
deadline=$(( $(date +%s) + 180 ))
until curl -sf "http://localhost:4566/_floci/health" >/dev/null 2>&1; do
  if [ "$(date +%s)" -ge "$deadline" ]; then
    docker compose logs --tail 50 floci >&2 || true
    die "Floci did not become healthy within 180s (logs above)."
  fi
  sleep 2
done

mount_src="$(docker container inspect "$FLOCI_CONTAINER_NAME" \
  --format '{{ range .Mounts }}{{ if eq .Destination "/app/data" }}{{ .Type }}:{{ .Source }}{{ end }}{{ end }}')"
case "$mount_src" in
  bind:*) log "Verified /app/data -> ${mount_src#bind:}" ;;
  "")     die "/app/data is not mounted at all. Check docker-compose.yml." ;;
  *)      warn "/app/data is a '$mount_src', not a host bind mount." ;;
esac

log "Floci is up at $FLOCI_ENDPOINT"
